on:
  push:
    branches:
      - "master"
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    
    - name: Set current date as env variable
      run: echo "NOW::$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo $NOW
          
    - name: Create local changes
      run: |
        curl -X GET https://www.meldkamerspel.com/einsaetze.json > nl_NL.json
        curl -X GET https://www.leitstellenspiel.de/einsaetze.json > de_DE.json
        curl -X GET https://www.meldkamerspel.com/alliance_event_types.json > events/nl_NL.json 
        
    - name: json-syntax-check
      uses: limitusus/json-syntax-check@v1
      with:
        pattern: "\\.json$"
        
    - name: Prettify code
      uses: creyD/prettier_action@v3.3
      with:
        # This part is also where you can pass other options, for example:
        prettier_options: --write **/*.{js,md,json}
        commit_message: "Update files"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
